database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  database: "minecraft"
playerdata:
  table: "player_data_table"
  # 可选 YAML / SQL
  # 如果选择SQL 会使用上面的表名和连接
  type: "YAML"
