setting:
  # 是否启用模块
  enable: false
  language: "zh_CN"

# 接受传送超时 (秒)
tpa-timeout: 30

# 接受请求后 (Tick) 后传送
tpa-delay: 10

# 执行Kether
actions:
  # 接受传送时
  accept:
    # 接受者
    self: |-
      tell inline "{{ &target }} 将在 0.5 秒后传送"
    # 传送者
    sent: |-
      tell inline "将在 0.5 秒后传送至 {{ &target }} "
  deny:
    self: |-
      tell "3"
    sent: |-
      tell "4"
  cancel:
    self: |-
      tell "1"
    sent: |-
      tell "2"