setting:
  # 是否启用模块
  enable: false
  language: "zh_CN"

# 接受传送超时 (秒)
tpa-timeout: 30

# 接受请求后 (Tick) 后传送
tpa-delay: 10

# 执行Kether
actions:
  accept:
    self: |-
      tell "1"
    sent: |-
      tell "2"
  deny:
    self: |-
      tell "3"
    sent: |-
      tell "4"